
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import fs from "node:fs";
import path from "node:path";
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const debugLog = (
  hypothesisId: string,
  message: string,
  data: Record<string, unknown>,
) => {
  // #region agent log
  fetch("http://127.0.0.1:7415/ingest/2082fc14-35c0-4e74-965a-10c1e9691abd", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Debug-Session-Id": "bca517",
    },
    body: JSON.stringify({
      sessionId: "bca517",
      runId: "initial",
      hypothesisId,
      location: "prisma.config.ts",
      message,
      data,
      timestamp: Date.now(),
    }),
  }).catch(() => {});
  // #endregion
};

const cwd = process.cwd();
const dotEnvPath = path.join(cwd, ".env");

debugLog("H1", "Prisma config evaluation started", {
  cwd,
  hasDatabaseUrlInProcessEnv: Boolean(process.env.DATABASE_URL),
  hasDotEnvFileInCwd: fs.existsSync(dotEnvPath),
  nodeEnv: process.env.NODE_ENV ?? null,
});

let databaseUrl: string;

try {
  debugLog("H2", "About to resolve DATABASE_URL via prisma env helper", {
    cwd,
    hasDatabaseUrlInProcessEnv: Boolean(process.env.DATABASE_URL),
  });
  databaseUrl = env("DATABASE_URL");
  debugLog("H3", "Resolved DATABASE_URL via prisma env helper", {
    hasDatabaseUrlAfterResolution: Boolean(databaseUrl),
  });
} catch (error) {
  const errorDetails =
    error instanceof Error
      ? { name: error.name, message: error.message }
      : { value: String(error) };

  debugLog("H4", "Failed to resolve DATABASE_URL via prisma env helper", {
    hasDatabaseUrlInProcessEnv: Boolean(process.env.DATABASE_URL),
    hasDotEnvFileInCwd: fs.existsSync(dotEnvPath),
    ...errorDetails,
  });

  throw error;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
